 
[connections.database]
# Database configuration will be added in Streamlit Cloud

# Jira Configuration
JIRA_URL = "https://yourcompany.atlassian.net"
JIRA_EMAIL = "your-email@company.com"
JIRA_API_TOKEN = "your-jira-api-token"

# Google AI Configuration
GOOGLE_API_KEY = "your-gemini-api-key"

# Authentication
SECRET_KEY = "your-production-secret-key"